apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-lewl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-lewl
    app.kubernetes.io/part-of: build-suite-test-application-ompu
  name: devfile-sample-hello-world-lewl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-lewl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-lewl
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-tgew-tenant/build-suite-test-application-ompu/devfile-sample-hello-world-lewl@sha256:8b6af74fc6ef2727379d672e83118b29a778ab60cd58fe18b02c1cff9c0682a4
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
